---
achievements:
  achievements:
    survived_pf1:
      type: community
      message: 'I Survived PF1: Ported over from Pathfinder 1E.'
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    portal: fa-globe
    fs3: fa-cubes
    story: fa-book
  permissions:
    manage_achievements: Award and remove achievements.
