---
pf2e_deities:
  Althea:
    allowed_alignments:
    - LG
    - NG
    - CG
    - LN
    - N
    divine_font:
    - heal
    divine_ability:
    - Intelligence
    - Charisma
    divine_skill: Medicine
    fav_weapon: halberd
    domains:
    - Family
    - Healing
    - Pain
    - Duty
    cleric_spells:
    - Soothe
    - Resilient Sphere
    - Unfettered Pack
    edicts:
    - Aid the suffering.
    - Shelter those in need.
    - Assist those who seek atonement.
    anathema:
    - Resort to violence when peace is feasible.
    - Use negative energy spells.
    - Betray the trust of a community.
  Angoron:
    allowed_alignments:
    - CG
    - NG
    - LG
    - N
    - CN
    - LN
    divine_font:
    - harm
    - heal
    divine_ability: Strength
    divine_skill: Athletics
    fav_weapon: maul
    domains:
    - Confidence
    - Might
    - Ambition
    - Freedom
    cleric_spells:
    - Ant Haul
    - Enlarge
    - Summon Giant
    edicts:
    - Protect those weaker than yourself.
    - Always try to do better than you did before.
    - Encourage the best in those around you.
    anathema:
    - Turn your back on a chance to challenge yourself.
    - Bully those weaker than yourself.
    - Fail to acknowledge when you’ve been bested.
#  Animus: SPOILER
#    allowed_alignments:
#    - NG
#    - LN
#    - N
#    - CN
#    divine_font:
#    - heal
#    - harm
#    divine_ability: Wisdom
#    divine_skill: Arcana
#    fav_weapon: quarterstaff
#    domains:
#    - Magic
#    - Glyph
#    - Knowledge
#    - Fate
#    cleric_spells:
#    - Magic Missile
#    - Telepathy
#    - Prismatic Spray
#    edicts:
#    - Teach and be taught.
#    - Serve the interests of magic.
#    - Preserve knowledge.
#    anathema:
#    - Take part in the destruction of knowledge.
#    - Allow passion to rule judgement.
#    - Use magic for pedestrian purposes.
  Caracoroth:
    allowed_alignments:
    - CN
    divine_font:
    - harm
    divine_ability:
    - Strength
    - Charisma
    divine_skill: Survival
    fav_weapon: unarmed
    domains:
    - Ambition
    - Destruction
    - Indulgence
    - Nightmares
    cleric_spells:
    - Magic Fang
    - Moon Frenzy
    - Mask of Terror
    edicts:
    - Follow your instincts.
    - Delight in destruction.
    - Reject the weak.
    anathema:
    - Be a coward.
    - Show weakness.
    - Talk when actions serve better.
  Ceinara:
    allowed_alignments:
    - NG
    - CG
    - CN
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Charisma
    divine_skill: Performance
    fav_weapon: rapier
    domains:
    - Fire
    - Passion
    - Change
    - Creation
    cleric_spells:
    - Charm
    - Fireball
    - Spirit Song
    edicts:
    - Embrace your passions.
    - Patronize the arts and inspiration in all its forms.
    - Delight in creation.
    anathema:
    - Support or protect the status quo, resort to rudeness when politeness will serve.
    - Discourage someone from their inspiration.
    - Hide your emotions for any reason.
  Daeus:
    allowed_alignments:
    - LG
    - NG
    - LN
    divine_font:
    - heal
    divine_ability:
    - Intelligence
    - Charisma
    divine_skill: Society
    fav_weapon: longsword
    domains:
    - Wyrmkin
    - Truth
    - Zeal
    - Sun
    cleric_spells:
    - True Strike
    - Fire Shield
    - Dragon Form
    edicts:
    - Justice isn’t perfect; always try to make it better.
    - Share the truths you learn.
    - Protect those who cannot defend themselves.
    anathema:
    - Abide injustice when you can step forward.
    - Choose for another who can choose for themselves.
    - Cheat, deceive, or undermine those who have placed trust in you.
  Dana:
    allowed_alignments:
    - NG
    - LN
    - N
    - CN
    divine_font:
    - heal
    - harm
    divine_ability: Charisma
    divine_skill: Nature
    fav_weapon: scimitar
    domains:
    - Earth
    - Nature
    - Change
    - Swarm
    cleric_spells:
    - Pummeling Rubble
    - Speak with Plants
    - Tangling Creepers
    edicts:
    - Defend nature’s bounty against those who would pillage it.
    - Honor the land as your mother; let none bring Her to harm.
    - Tend the gardens of the earth in all their forms.
    anathema:
    - Engage in wanton destruction.
    - Tolerate the poisoning of the earth.
    - Hunt rampantly.
  Deimos:
    allowed_alignments:
    - LN
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Charisma
    divine_skill: Deception
    fav_weapon: light hammer
    domains:
    - Decay
    - Secrecy
    - Trickery
    - Vigil
    cleric_spells:
    - Illusory Disguise
    - Crushing Despair
    - Duplicate Foe
    edicts:
    - Call out the flaws in all things.
    - Reinforce the belief in the worst of people.
    - Allow nothing to hold you back.
    anathema:
    - Attempt to bolster another's confidence.
    - Remain silent where you can speak.
    - Believe in innocence.
  Eluna:
    allowed_alignments:
    - LG
    - NG
    - CG
    - LN
    - N
    divine_font:
    - heal
    divine_ability:
    - Intelligence
    - Wisdom
    divine_skill: Arcana
    fav_weapon: starknife
    domains:
    - Moon
    - Magic
    - Dreams
    - Change
    cleric_spells:
    - Sleep
    - Scrying
    - Dream Council
    edicts:
    - Take the long view and always consider the greater good of all.
    - Must use magic responsibly, and challenge those who do not.
    - Seek to rescue those lycanthropes you can from the grip of Caracoroth.
    anathema:
    - Use spells or magic that deny the target their free will.
    - Sacrifice the future for short-term benefit.
    - Ignore the guidance found in dreams, divination, and prophecy.
  Gilead:
    allowed_alignments:
    - NG
    - CG
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Dexterity
    divine_skill: Survival
    fav_weapon: longbow
    domains:
    - Earth
    - Nature
    - Travel
    - Air
    cleric_spells:
    - Longstrider
    - Wall of Thorns
    - Unfettered Pack
    edicts:
    - Honor the Hunt.
    - Defend wild spaces.
    - Kill only what you need.
    anathema:
    - Kill uncleanly and mercilessly.
    - Smother the wild rather than protect it.
    - Hoard the resources of the wilderness.
  Gunahkar:
    allowed_alignments:
    - N
    - CN
    divine_font:
    - harm
    divine_ability: Constitution
    divine_skill: Survival
    fav_weapon: guisarme
    domains:
    - Destruction
    - Death
    - Indulgence
    - Void
    cleric_spells:
    - Grim Tendrils
    - Paralyze
    - Blister
    edicts:
    - Do not stop suffering.
    - Do not fear sickness.
    - Endure all you can.
    anathema:
    - Stop the faithful from feeling their pain.
    - Fail to endure a trial.
    - Seek treatment for personal problems.
  Illotha:
    allowed_alignments:
    - LN
    - CN
    divine_font:
    - harm
    divine_ability: Constitution
    divine_skill: Society
    fav_weapon: kukri
    domains:
    - Cold
    - Fate
    - Pain
    - Undeath
    cleric_spells:
    - Ill Omen
    - Ice Storm
    - True Target
    edicts:
    - Punish those that harm you.
    - Vengeance is sweet.
    - Get the justice you deserve.
    anathema:
    - Let someone get away with hurting you.
    - Fail to punish someone that's done wrong.
    - Ignoring someone's quest for vengeance.
  Kor:
    allowed_alignments:
    - CG
    - CN
    - N
    divine_font:
    - harm
    divine_ability: Strength
    divine_skill: Intimidation
    fav_weapon: greataxe
    domains:
    - Zeal
    - Pain
    - Might
    - Destruction
    cleric_spells:
    - Jump
    - Haste
    - Weapon Storm
    edicts:
    - Be brave enough to fight at My side.
    - Be wise enough to achieve a glorious death.
    - Be prepared to train to achieve glory.
    anathema:
    - Be the first to leave the battlefield.
    - Mistake bravery for foolishness.
    - Lie about your accomplishments.
  Maugrim:
    allowed_alignments:
    - LN
    - N
    divine_font:
    - harm
    divine_ability: Constitution
    divine_skill: Intimidation
    fav_weapon: greatsword
    domains:
    - Ambition
    - Toil
    - Tyranny
    - Perfection
    cleric_spells:
    - Phantom Pain
    - Dominate
    - Force Cage
    edicts:
    - Never cease your toil.
    - A hard day's work is its own reward.
    - You are entitled to what you earn.
    anathema:
    - Being lazy.
    - Shirking duties.
    - Taking more than you're owed.
  Navos:
    allowed_alignments:
    - LG
    - NG
    - LN
    - N
    divine_font:
    - heal
    divine_ability: Wisdom
    divine_skill: Acrobatics
    fav_weapon: unarmed
    domains:
    - Time
    - Secrecy
    - Perfection
    - Star
    cleric_spells:
    - Deja Vu
    - Dimension Door
    - Blanket of Stars
    edicts:
    - Learn from the past; do not dwell on it.
    - Be aware that you are making history now.
    - Seek to encourage the balance of time.
    anathema:
    - Be consumed by something you cannot change.
    - Fail to perceive your own actions.
    - Try to change past events.
  Rada:
    allowed_alignments:
    - CG
    - LN
    - CN
    divine_font:
    - heal
    - harm
    divine_ability: Wisdom
    divine_skill: Diplomacy
    fav_weapon: trident
    domains:
    - Water
    - Wealth
    - Travel
    - Air
    cleric_spells:
    - Hydraulic Push
    - Mariner's Curse
    - Horrid Wilting
    edicts:
    - Honor a fair trade.
    - The sea is owed a portion of your keep.
    - Harvest only what you need.
    anathema:
    - Break a fair bargain.
    - Be a false guide to another.
    - Pollute the ocean.
  Reos:
    allowed_alignments:
    - LG
    - NG
    - LN
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Wisdom
    divine_skill: Crafting
    fav_weapon: warhammer
    domains:
    - Earth
    - Creation
    - Perfection
    - Toil
    cleric_spells:
    - Telekinetic Projectile
    - Creation
    - Fiery Body
    edicts:
    - Always tinker - a thing can always be better.
    - Respect honest effort, even lacking in skill.
    - Respect expertise.
    anathema:
    - Engage in wanton destruction.
    - Strive for impossible perfection.
    - Disrespect the act of creation.
  Serriel:
    allowed_alignments:
    - LG
    - LN
    - NG
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Intelligence
    divine_skill: Society
    fav_weapon: lance
    domains:
    - Cities
    - Protection
    - Duty
    - Wealth
    cleric_spells:
    - Ant Haul
    - Wall of Stone
    - True Target
    edicts:
    - Enrich your community.
    - Honor the ways of other communities.
    - A thriving community is a growing one.
    anathema:
    - Enrich yourself at the expense of your community.
    - Refuse to defend your community.
    - Vandalize a piece of cultural heritage.
  Taara:
    allowed_alignments:
    - N
    - CN
    divine_font:
    - harm
    divine_ability: Wisdom
    divine_skill: Deception
    fav_weapon: spiked chain
    domains:
    - Void
    - Darkness
    - Magic
    - Secrecy
    cleric_spells:
    - Illusory Disguise
    - Secret Page
    - Glibness
    edicts:
    - Learn and tell your stories as often as possible.
    - Keep your secrets.
    - Unearth the secrets of others.
    anathema:
    - Never shatter someone's illusions.
    - Allow the truth to ruin a good story.
    - Give your secrets away for free.
  Tarien:
    allowed_alignments:
    - NG
    - CG
    - CN
    - N
    divine_font:
    - heal
    divine_ability: Charisma
    divine_skill: Stealth
    fav_weapon: Short Sword
    domains:
    - Luck
    - Travel
    - Trickery
    - Confidence
    cleric_spells:
    - Pass Without Trace
    - Hideous Laughter
    - Synesthesia
    edicts:
    - Find the small joys in everything.
    - Understand that humility is the greatest teacher.
    - It's only funny if others laugh too.
    anathema:
    - Make a joke of someone who doesn’t deserve it.
    - Dogpile someone already being shamed.
    - Ringing harm with your humor.
  Thul:
    allowed_alignments:
    - LN
    - N
    - CN
    divine_font:
    - harm
    divine_ability: Wisdom
    divine_skill: Occultism
    fav_weapon: scythe
    domains:
    - Undeath
    - Indulgence
    - Decay
    - Cold
    cleric_spells:
    - Object Reading
    - Modify Memory
    - Polar Ray
    edicts:
    - Do not fear death.
    - Gather as much experience as you can.
    - Serve the dead where you can.
    anathema:
    - Fail to preserve memories.
    - Ignore the needs of the dead.
    - Live in fear of death.
  Vardama:
    allowed_alignments:
    - LG
    - NG
    - LN
    - N
    divine_font:
    - heal
    - harm
    divine_ability: Intelligence
    divine_skill: Medicine
    fav_weapon: khopesh
    domains:
    - Death
    - Sorrow
    - Repose
    - Soul
    cleric_spells:
    - Soothe
    - Ghostly Weapon
    - Disintegrate
    edicts:
    - Guard the rest of the peaceful dead.
    - Offer succor to the grieving.
    - Try to ensure a peaceful passing.
    anathema:
    - Disturb the rest of the dead.
    - Judge the worth of a person.
    - Command the fate of a soul.
