---
website:
  achievements:
    wiki_create:
      type: portal
      message: Created a wiki page.
    wiki_edit:
      type: portal
      message: Edited a wiki page.
  allow_html_in_markdown: true
  auto_wiki_export: true
  character_gallery_group: Region
  character_gallery_subgroup: ''
  left_sidebar: false
  max_folder_size_kb: 2000
  max_upload_size_kb: 300
  permissions:
    manage_theme: Edit web portal CSS and colors.
    manage_wiki: Create and delete restricted wiki pages.
  restricted_pages:
  - home
  - policy:*
  - rules:*
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: Play
    menu:
    - title: Create a Character
      route: chargen
    - divider: true
    - title: Play
      route: play
    - title: Active Scenes
      route: scenes-live
    - title: Unshared Scenes
      route: scenes-unshared
    - title: Start New Scene
      route: scene-create
    - divider: true
    - title: Who's Online
      route: who
    - title: Forum
      route: forum
    - title: Mail
      route: mail
    - title: Events
      route: events
    - divider: true
    - title: Web Client
      route: client
  - title: Directory
    menu:
    - title: Characters
      route: characters
    - title: Scenes
      route: scenes
    - title: Plots
      route: plots
    - divider: true
    - title: Players
      route: players
    - title: Game Admin
      route: admins
    - title: Census
      route: census
    - title: Locations
      route: locations
    - title: Combats
      route: combats
    - divider: true
    - title: Files
      route: files
#  - title: The World of Ea
#    menu:
#    - title: World Map
#      route: wiki-page
#      id: theme:world_map
#    - title: Ea's History
#      route: wiki-page
#      id: theme:world_history
#    - title: Timeline
#      route: wiki-page
#      id: theme:timeline
#    - title: Languages of Ea
#      route: wiki-page
#      id: theme:languages
#    - title: Deities
#      route: wiki-page
#      id: theme:deities
#    - title: Regions
#      route: wiki-page
#      id: theme:regions
  - title: System
    menu:
    - title: Playtest Overview
      route: wiki-page
      id: rules:playtest-overview
    - divider: true
    - target: blank
      title: AON PRD <i class="fa fa-external-link-alt" aria-hidden="true">
      url: https://2e.aonprd.com/
  - title: Wiki
    menu:
    - title: Home
      route: wiki
    - divider: true
    - title: Create New Page
      route: wiki-create
    - title: All Pages
      route: wiki-all
    - title: Search Wiki
      route: search-wiki
    - title: Tags
      route: wiki-tags
    - title: Recent Changes
      route: recent-changes
    - divider: true
    - title: Files
      route: files
    - id: markdown
      title: Editing Help
      route: help-topic
  - title: Help
    menu:
    - title: Requests
      route: jobs
    - title: Account
      route: account
    - divider: true
    - title: Game Help
      route: help
    - title: Search
      route: search-wiki
    - id: markdown
      title: Markdown Reference
      route: help-topic
    - title: Emoji Reference
      route: emoji
    - title: Terms of Service
      route: tos
    - divider: true
    - target: blank
      title: MUSH 101 Tutorial <i class="fa fa-external-link-alt" aria-hidden="true">
      url: https://aresmush.com/mush-101/
  - title: Admin
    roles:
    - admin
    - coder
    menu:
    - title: Jobs
      route: jobs
    - title: Setup
      route: setup
    - title: Manage
      route: manage
    - title: Logs
      route: logs
    - title: Files
      route: files
    - title: Roles
      route: roles
    - title: Server
      route: server-info
  - title: Code
    roles:
    - coder
    menu:
    - title: Tinker
      route: tinker
    - title: Custom Code
      route: custom-code
  - title: Theme
    roles:
    - admin
    menu:
    - title: Theme Colors
      route: setup-colors
    - title: Custom Styles
      route: textfile
      ids:
      - style
      - custom_style.scss
    - title: Files
      route: files
    - title: Home Page Text
      route: textfile
      ids:
      - text
      - website.txt
  - title: "<i class='fas fa-magnifying-glass'/>"
    menu:
    - title: Search Characters
      route: search-chars
    - title: Search Scenes
      route: search-scenes
    - title: Search Locations
      route: search-locations
    - title: Search Wiki
      route: search-wiki
    - title: Search Help
      route: search-help
    - title: Search Forum
      route: search-forum
    - title: Search Jobs/Requests
      route: search-jobs
  uploadable_extensions:
  - ".jpg"
  - ".png"
  - ".gif"
  - ".jpeg"
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: home
  wiki_export_cron:
    hour:
    - 3
    minute:
    - 37
  shortcuts:
    wiki: website
    website/archive: website/export
  hide_searchbox: true
